apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-ss-md-hack-
spec:
  pipelineRef:
    name: build-and-push
  params:
    - name: repo-url
      value: https://github.com/electrified/ss-rom-hack.git
    - name: revision
      value: main
    - name: image-name
      value: 192.168.1.9:32000/ss-md-hack
    - name: image-tag
      value: latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc
